### ISSUE TITLE
[ Pending issues ] Milestone 2.1

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#147]
**Type size**
- [x] Type size setting isn't working for paragraphs (OK)
- [x] At toolbar, touching outside type size settings should close popup 

**Dark mode** (PRIORITÁRIO)
- [x] o site deveria abrir com o dark mode ativo se o dispositivo está configurado para mostrar desta forma
- [x]  links do bloco newspack dentro do single (OK)
![image](https://user-images.githubusercontent.com/12487823/90171213-888cd880-dd77-11ea-9bf0-e4ae01346408.png)

COMENTÁRIO DO STEFANO:
- Aqui está o caminho das pedras: https://nandovieira.com.br/implementando-dark-mode-em-conteudo-web. São mudanças no CSS, essencialmente.
- E aqui está como adicionar um botão para ativar ou desativar o dark mode e salvar as preferências do usuário usando, para isso, o LocalStorage do navegador com JS ou cookie com PHP: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#combining

**Headings**
- [x] Title looks smaller than H1: (Fixed in #156)
![image](https://user-images.githubusercontent.com/12487823/90028643-53598b00-dc90-11ea-9131-a24ea21d1247.png)

**Newsletter block**
- [x] Thank you notice should appear below "Lorem ipsum" message on newsletter subscription form (desktop & mobile): (OK)
![image](https://user-images.githubusercontent.com/12487823/90028726-6bc9a580-dc90-11ea-96d4-b9c4e5e46ba2.png)

Update mailchimp form
```
<div class="input-group">
  <input type="email" name="EMAIL" required class="form-control" placeholder="your email" aria-label="Recipient's username" aria-describedby="basic-addon2">
  <div class="input-group-append">
    <button class="btn btn-outline-secondary" type="submit">
      <i class="fas fa-arrow-right d-block d-sm-none mc4wp__btn-icon" ></i> <span class="d-none d-sm-block mc4wp__btn-label">SUBSCRIBE NOW</span></button>
  </div>
</div>
<p class="link">Lorem ipsum sit amet dolo <a href="#">hyperlink</a></p>
```

**Image Slider**
- [x] Caption in the slider is at the wrong position. On mobile it should be below the photo, not over it. Please check Paisifika's  homepage for a reference: (OK)
https://invis.io/7RX2LFD2UVW#/421658266_Mobile_InfoPacific_Home 

**Credited image**
- [x] Fix credit position when credited image is fullwidht  (OK)
![image](https://user-images.githubusercontent.com/12487823/90245721-97bc6680-de09-11ea-89f1-409d33763925.png)
Here: the credited image's credit when image is fullwidth appears in wrong position
https://mekongeye-jeo.hacklab.com.br/topic/world/2020/07/be-proud-of-being-latin-american/
![image](https://user-images.githubusercontent.com/12487823/90247047-2c27c880-de0c-11ea-81f5-c893635bb368.png)

**Sub menu** DESPRIORIZADO
- [] The "more" menu will be below "Follow us" (OK)
- [ ] The more submenu should be aligned with the "more ->" option
![image](https://user-images.githubusercontent.com/12487823/90352735-8eeeaf00-e01a-11ea-95bd-b5ae98741378.png)
 
**WPML languages**
- [x] The languages available will be in the top bar as image below. (OK)
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/415582872/preview?scrollOffset=3966.666748046875
![image](https://user-images.githubusercontent.com/12487823/90245998-12858180-de0a-11ea-8058-eeadb784876a.png)

**Sorry block**
- [ NOT A BUG ] If post has few content with a credited image and sorry section, layout breaks as:
![image](https://user-images.githubusercontent.com/12487823/90171902-9abb4680-dd78-11ea-975d-130848bb936f.png)

**Comment by isaquemelo** [comment]
**Type size**
- Type size setting isn't working for paragraphs: 
![image](https://user-images.githubusercontent.com/7103838/90255310-7c0d8c00-de1a-11ea-9c45-111e2a89c339.png)
The "Font size" panel must be configured to use relative units (rem or em) to support the toolbar `font-size` alteration.
