### ISSUE TITLE
[ Bugs do Milestone 2.2 ]

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#181]
Fixes done:
- [x] Fix: link "see last edition" in vertical newsletter
![image](https://user-images.githubusercontent.com/12487823/90763042-6554b280-e2bc-11ea-8fe9-7dc612bba2ab.png)

- [x] Fix: Custom decoration aligned with category name in Category Page
![image](https://user-images.githubusercontent.com/12487823/90763110-84534480-e2bc-11ea-96d8-cca99ad775a5.png)

- [x] Fix: Update font-size for "author" label in Author Page when custom decoration is used

![image](https://user-images.githubusercontent.com/12487823/90763203-a3ea6d00-e2bc-11ea-883f-2ccf01613da5.png)

- [x] Fix: the the top bar in mobile mode
![image](https://user-images.githubusercontent.com/12487823/90763260-bf557800-e2bc-11ea-8a27-ca362dfcda92.png)

- [x] Fix in home_sidebar blocks in MekongEye and Ekuatorial site. This block according to layout must have:

`border-radius: 10px 10px 0 0;
`
![image](https://user-images.githubusercontent.com/12487823/90763314-dac08300-e2bc-11ea-9f75-c27538ecde73.png)
![image](https://user-images.githubusercontent.com/12487823/90763482-27a45980-e2bd-11ea-8d43-ab789b48b072.png)

- [x] Fix in pages: widgets "after post" as newsletter MUSTN'T be in Pages
![image](https://user-images.githubusercontent.com/12487823/90763604-591d2500-e2bd-11ea-99f5-cd5cb2f14d3e.png)

- [x] Fix in Posts: The homepage_block of newspack must use the primary-font.
![image](https://user-images.githubusercontent.com/12487823/90763723-92559500-e2bd-11ea-93d4-dd3d072406d3.png)

- [x] Fix: The hamburger menu MUST appear in sticky header for post
![image](https://user-images.githubusercontent.com/12487823/90763694-836ee280-e2bd-11ea-9758-8862f1850352.png)

 - [x] Fix: The search field is hidden by mobile's keyboard
![image](https://user-images.githubusercontent.com/12487823/90765465-58d25900-e2c0-11ea-9ec8-205409dd825c.png)
