### ISSUE TITLE
[ Bugs do Milestone 2.2 - Part 2]

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#182]
- [x] Fix for contact form (bootstrap) in mobile

![image](https://user-images.githubusercontent.com/12487823/90785951-592b1e00-e2d9-11ea-82e8-b1765e430dbd.png)

- [x] After updating a post, all options for featured image appears again
![image](https://user-images.githubusercontent.com/12487823/90786016-719b3880-e2d9-11ea-9411-72c45fa1a84e.png)

- [x] Widget are not available in Customize for Post, Category, Tags, Author

![image](https://user-images.githubusercontent.com/12487823/90786360-dc4c7400-e2d9-11ea-8f18-7300f5aeb5f1.png)
